/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`

declare namespace Cloudflare {
	interface Env {
		// R2 Object Storage (auto-generated by wrangler types)
		R2_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		
		// Webflow API Configuration (custom environment variables)
		WEBFLOW_API_HOST?: string;
		WEBFLOW_SITE_API_TOKEN?: string;
		WEBFLOW_CMS_SITE_API_TOKEN?: string;
		WEBFLOW_CMS_SITE_API_TOKEN_WRITE?: string;
		
		// Collection IDs
		GUESTBOOK_COLLECTION_ID?: string;
		TIMELINE_COLLECTION_ID?: string;
		
		// Optional: Custom public domain for R2 (if using custom domain)
		R2_PUBLIC_DOMAIN?: string;
		R2_PUBLIC_URL?: string;
		
		// Cloudflare Account ID (provided by Webflow Cloud)
		CLOUDFLARE_ACCOUNT_ID?: string;
	}
}

interface Env extends Cloudflare.Env {}
